package servers

import (
	"claseobrera/app/routers"

	"github.com/gofiber/fiber/v2"
)

func SetupAndListen() {
	app := fiber.New()

	routers.OrganizacionGeneralRoutes(app)
	routers.OrganizacionJerarquiaRoutes(app)
	routers.OrganizacionEstructuraRoutes(app)
	routers.EstadosRoutes(app)
	routers.MunicipiosRoutes(app)
	routers.ParroquiasRoutes(app)
	routers.CiudadesRoutes(app)
	routers.InstitucionesRoutes(app)
	routers.SessionRoutes(app)
	routers.UsersRoutes(app)
	routers.PermisosRoutes(app)
	routers.RolesRoutes(app)
	routers.PerfilesRoutes(app)
	routers.CargoPublicoRoutes(app)
	routers.CargoOnapreRoutes(app)
	routers.CentrosVotacionRoutes(app)
	routers.ComunaRoutes(app)
	routers.ConsejoComunalRoutes(app)
	routers.EstadoCivilRoutes(app)
	routers.GeneroRoutes(app)
	routers.EstructuraPopularRoutes(app)
	routers.MovimientosSocialesRoutes(app)
	routers.NivelAcademicoRoutes(app)
	routers.PartidoPoliticoRoutes(app)
	routers.ResponsabilidadPoliticaRoutes(app)
	routers.ParentescoRoutes(app)
	routers.DepartamentosRoutes(app)
	routers.FuerzaPoliticaRoutes(app)
	routers.HorarioRoutes(app)
	routers.InstitucionExtracademicaRoutes(app)
	routers.MarcaVehiculoRoutes(app)
	routers.MisionesBaseRoutes(app)
	routers.ReposoMedicoRoutes(app)
	routers.ResponsabilidadComunalRoutes(app)
	routers.TipoEnfermedadRoutes(app)
	routers.TipoFormacionExtracademicaRoutes(app)
	routers.TipoHabilidadRoutes(app)
	routers.TipoParentescoRoutes(app)
	routers.TipoSueloViviendaRoutes(app)
	routers.TipoTechoRoutes(app)
	routers.AcademicaParentescoRoutes(app)
	routers.AmonestacionesRoutes(app)
	routers.AntecedentesMedicosRoutes(app)
	routers.AsistenciaRoutes(app)
	routers.AsistenciaBiometricaRoutes(app)
	routers.BioquimicosObreroRoutes(app)
	routers.CertificacionRoutes(app)
	routers.ConstanciaRoutes(app)
	routers.DatosLaboralesRoutes(app)
	routers.DiaFeriadoRoutes(app)
	routers.DireccionObreroRoutes(app)
	routers.GestionExtracademicaRoutes(app)
	routers.HabilidadesRoutes(app)
	routers.GestionHorarioRoutes(app)
	routers.InstitucionAcademicaRoutes(app)
	routers.JustificacionAusenciaRoutes(app)
	routers.GestionParentescoRoutes(app)
	routers.PermisoAsistenciaRoutes(app)
	routers.PoliticoObreroRoutes(app)
	routers.RegistroTalentoHumanoRoutes(app)
	routers.SaludParentescoRoutes(app)
	routers.SolicitudEgresoRoutes(app)
	routers.SaludParentescoRoutes(app)
	routers.TitulosAcademicosRoutes(app)
	routers.GestionUnoxDiezRoutes(app)
	routers.VehiculoObreroRoutes(app)
	routers.ViviendaRoutes(app)
	routers.AcademicaParentescoRoutes(app)
	routers.TipoParedesRoutes(app)
	routers.GeoEventosRoutes(app)
	routers.AsistenciaEventosRoutes(app)
	routers.EventosPopularesRoutes(app)



	app.Listen(":3000")
}
